<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <LangVersion>preview</LangVersion>

	  <RootNamespace>MadWizard.Desomnia.Session</RootNamespace>
    <AssemblyName>DesomniaSessionMonitor</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DesomniaCore\DesomniaCore.csproj" />
    <ProjectReference Include="..\NetworkMonitor\NetworkMonitor.csproj" />
    <ProjectReference Include="..\ProcessMonitor\ProcessMonitor.csproj" />
  </ItemGroup>

</Project>
