<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MadWizard.Desomnia.NetworkSession</RootNamespace>
    <AssemblyName>DesomniaNetworkSessionMonitor</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DesomniaCore\DesomniaCore.csproj" />
    <ProjectReference Include="..\NetworkMonitor\NetworkMonitor.csproj" />
  </ItemGroup>

</Project>
